### ISSUE TITLE
Invitation to contribute to pandas-profiling

### ISSUE THREAD

**Issue by sbrugman** [obaig47/profilingGui#1]
Hi,

I see that you are working on a PyQt GUI for pandas-profiling.
We've made some progress in that direction too in the past. Would you be interested in working on the main project? That way your work could reach thousands of users :)

The Qt-specific code can be found here:
https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/__init__.py#L256
https://github.com/pandas-profiling/pandas-profiling/tree/master/src/pandas_profiling/report/presentation/flavours/qt

Kind regards,
Simon

**Comment by obaig47** [comment]
Hi Simon, 

I will most certainly do that in the future instead of working here.
